###################### Filebeat Configuration Example #########################

#=========================== Filebeat prospectors =============================

filebeat.prospectors:

- type: log
  enabled: true
  paths:
    	 - ${LOG_PATH:<update this path to point ${karaf.data}/eventmonitoring/em*.log*}
  fields:
  app_id: ${APP_NAME:ESB}
  fields_under_root: true
  json.keys_under_root: true
  json.message_key: log

logging.metrics.enabled: false

#In this example, the pattern matches the following lines:
#    a line that begins with spaces followed by the word at or ...
#    a line that begins with the words Caused by: 

#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["${LOGSTASH_HOSTS:localhost}:${LOGSTASH_PORT:5044}"]

